### ISSUE TITLE
Respond to 10+ digits

### ISSUE THREAD

**Issue by kawaguti** [kawaguti/mogiri#6]
It responds to number sequences of 10 digits or more.

10桁以上の数字列に反応してしまう。
> https://discord.com/channels/697437131328585810/812613081741393951/839450378047455264

**Comment by springaki** [comment]
https://discord.com/channels/697437131328585810/812613081741393951/840524277942059023
![スクリーンショット 2021-05-08 18 43 39](https://user-images.githubusercontent.com/534628/117534643-4f934300-b02d-11eb-892f-d7deeaef2140.png)
```
Aki (spring.aki) — 今日 18:43
@Admin テスト
mogiri ボット  — 今日 18:43
@Aki (spring.aki), あら、7857922659はEventbrite上に見当たりませんでした。10桁のOrder番号をご確認ください。
```

となったので、 `@スクフェス大阪運営` メンションが ID として処理されてる様子
